### PR TITLE
Implemented JSON serialization

### PR DESCRIPTION
**Pull request by DottD**
Hi, first of all I really like your work. In my project I faced the need to serialize the KDTree and I thought that the easiest way to achieve that was directly editing the source code. Please, have a look at the changes I made and if you feel that they conform to your project guidelines, let's merge them.

Below is a summary of changes, that you can also find in my commit. I am sorry I didn't implement a test for the new features, but I can work on it if you think that it is needed.

Bests
Filippo

```
KDTree and Node are now convertible to/from JSON.
Types are a bit stricter, in order to easily convert to/from JSON.
Three computed property have been added for convenience, namely height, length, depth.
points attribute removed, because it was never used.
```

### CODE REVIEW

**Comment by JankoLancer** [comment]
Hi, @DottD thank for your contribution!
I like your work, especially a part for JSON serialization. This way we can achieve to only one time create Tree and next read just read it from a file!

I have one question for constructor parameters. For me, it is ok to delete points from KDTree class, but if make points optional for a constructor, we make breaking changes for this package. Also, what is the point of creating empty Tree, do you have some special case?  What you think about  making constructor like this:

`KDTree(List<Map> points, this.metric, this.dimensions)`?

**Comment by DottD** [comment]
Hi Janko,

Sorry for my late reply, I’ve been a bit busy with my work. I’m very happy that you like my little contribution! :)

As for the construction parameters, in my app I just define an empty tree and the user fills it in, an element at a time. Anyway there are no issues with either choices, so if you prefer keeping the old signature it’s fine also for my use case, I will just add an empty list as the first argument.

Filippo

**Comment by JankoLancer** [comment]
You are right, this is a good example of why we need points to be an optional parameter.

I notice a possible problem: When we make-instance of a tree with `fromJson` constructor we lose `metric` function. Later on, `nearest` method use this `metric` function. What do you think about this problem?

**Comment by DottD** [comment]
You're right and I forgot to mention it. In my app's code I handled that problem by reassigning the `metric` from the outside. I understand that this is not very convenient, because a user could mistakenly change the metric after loading an instance of `KDTree`, but I have no other idea. I tried to do some research but it seems that function serialization is not common in dart. Any idea? Perhaps we may add some check on the `metric` in the `nearest` function?

**Comment by JankoLancer** [comment]
For now, we should throw Exception from nearest function with an appropriate message.
I will look for a better solution later on.

**Comment by DottD** [comment]
Now the `nearest` function checks for undefined metric function and eventually throws. Please check if these modifications are as you expected.

**Comment by JankoLancer** [comment]
I have merged your PR, but I revert constructor to an old version, I think that is best for all.
If you wish, you can add instruction about JSON in the readme.

Thank you again for your contribution.

**Pull request merged**
